import {
  siAndroid,
  siAngular,
  siAnsible,
  siAntdesign,
  siAnthropic,
  siApache,
  siApacheairflow,
  siApacheflink,
  siApachehadoop,
  siApachekafka,
  siApachespark,
  siApollographql,
  siApple,
  siAppwrite,
  siArgo,
  siArchlinux,
  siAsana,
  siAstro,
  siAuth0,
  siBabel,
  siBitbucket,
  siBlender,
  siBootstrap,
  siBun,
  siC,
  siCircleci,
  siClickhouse,
  siClaude,
  siClaudecode,
  siCloudflare,
  siCockroachlabs,
  siConfluence,
  siConsul,
  siContainerd,
  siCplusplus,
  siCss,
  siCursor,
  siCypress,
  siDart,
  siDatabricks,
  siDatadog,
  siDebian,
  siDeno,
  siDigitalocean,
  siDiscord,
  siDjango,
  siDocker,
  siDotnet,
  siDuckdb,
  siElastic,
  siElasticsearch,
  siElectron,
  siElixir,
  siEsbuild,
  siEslint,
  siExpress,
  siFastapi,
  siFedora,
  siFigma,
  siFirebase,
  siFlask,
  siFlutter,
  siFlux,
  siForgejo,
  siGit,
  siGitea,
  siGithub,
  siGithubactions,
  siGithubcopilot,
  siGitlab,
  siGo,
  siGoogle,
  siGooglebigquery,
  siGooglecloud,
  siGooglecolab,
  siGooglegemini,
  siGrafana,
  siGraphql,
  siHashicorp,
  siHashnode,
  siHaskell,
  siHelm,
  siHomeassistant,
  siHtml5,
  siHuggingface,
  siInfluxdb,
  siInsomnia,
  siIntellijidea,
  siIstio,
  siJaeger,
  siJavascript,
  siJenkins,
  siJest,
  siJira,
  siJupyter,
  siKeras,
  siKeycloak,
  siKotlin,
  siKubernetes,
  siLangchain,
  siLaravel,
  siLinear,
  siLinkerd,
  siLinux,
  siLooker,
  siLua,
  siMdnwebdocs,
  siMedium,
  siMetabase,
  siMetaai,
  siMinio,
  siMiro,
  siMistralai,
  siMlflow,
  siMongodb,
  siMui,
  siMysql,
  siNeo4j,
  siNestjs,
  siNetlify,
  siNeovim,
  siNewrelic,
  siNextdotjs,
  siNginx,
  siNodedotjs,
  siNotion,
  siNpm,
  siNumpy,
  siOkta,
  siOllama,
  siOpencv,
  siOpenapiinitiative,
  siOpenjdk,
  siOpensearch,
  siOpentelemetry,
  siOpentofu,
  siPacker,
  siPandas,
  siPaypal,
  siPerl,
  siPhp,
  siPlanetscale,
  siPnpm,
  siPodman,
  siPostgresql,
  siPostman,
  siPrettier,
  siPrisma,
  siPrometheus,
  siPulumi,
  siPytorch,
  siPython,
  siR,
  siRabbitmq,
  siRaspberrypi,
  siRay,
  siReact,
  siReactquery,
  siReddit,
  siRedis,
  siRedux,
  siReplicate,
  siRollupdotjs,
  siRuby,
  siRust,
  siSass,
  siScala,
  siScikitlearn,
  siSentry,
  siSnowflake,
  siSolidity,
  siSonar,
  siSonarqubeserver,
  siSourcehut,
  siSplunk,
  siSpring,
  siSqlite,
  siStackoverflow,
  siStorybook,
  siStripe,
  siSupabase,
  siSvelte,
  siSwagger,
  siSwift,
  siTailwindcss,
  siTauri,
  siTeamcity,
  siTensorflow,
  siTerraform,
  siThreedotjs,
  siTraefikproxy,
  siTravisci,
  siTrello,
  siTrpc,
  siTypescript,
  siUbuntu,
  siUnity,
  siVault,
  siVercel,
  siVite,
  siVim,
  siVitest,
  siVscodium,
  siVuedotjs,
  siWebassembly,
  siWebpack,
  siWeightsandbiases,
  siX,
  siYarn,
  siYoutube,
  siZedindustries,
  siZig,
  type SimpleIcon,
} from "simple-icons"

export type BrandIconDef = {
  title: string
  aliases: string[]
  icon: SimpleIcon | { kind: "mark"; letters: string }
}

function si(icon: SimpleIcon, aliases: string[] = []): BrandIconDef {
  return { title: icon.title, aliases, icon }
}

function mark(title: string, letters: string, aliases: string[] = []): BrandIconDef {
  return { title, aliases, icon: { kind: "mark", letters } }
}

export const BRAND_ICONS = {
  github: si(siGithub, ["gh"]),
  gitlab: si(siGitlab, ["gl"]),
  bitbucket: si(siBitbucket, ["bb"]),
  git: si(siGit, ["vcs"]),
  gitea: si(siGitea),
  forgejo: si(siForgejo),
  sourcehut: si(siSourcehut, ["srht", "source hut"]),
  docker: si(siDocker, ["containers"]),
  kubernetes: si(siKubernetes, ["k8s", "kube"]),
  helm: si(siHelm, ["charts"]),
  podman: si(siPodman),
  containerd: si(siContainerd),
  google: si(siGoogle, ["alphabet"]),
  "google-cloud": si(siGooglecloud, ["gcp", "gcloud"]),
  colab: si(siGooglecolab, ["google colab", "colaboratory"]),
  gemini: si(siGooglegemini, ["google gemini", "bard"]),
  bigquery: si(siGooglebigquery, ["bq", "google bigquery"]),
  tensorflow: si(siTensorflow, ["tf"]),
  pytorch: si(siPytorch, ["torch"]),
  anthropic: si(siAnthropic, ["ai"]),
  claude: si(siClaude, ["anthropic claude", "ai"]),
  "claude-code": si(siClaudecode, ["ai"]),
  huggingface: si(siHuggingface, ["hf", "transformers", "ai"]),
  ollama: si(siOllama, ["local llm", "ai"]),
  langchain: si(siLangchain, ["lc", "ai"]),
  mistral: si(siMistralai, ["mistral ai", "ai"]),
  "meta-ai": si(siMetaai, ["llama", "ai"]),
  replicate: si(siReplicate, ["ai"]),
  cursor: si(siCursor, ["ide", "ai"]),
  copilot: si(siGithubcopilot, ["github copilot", "ai"]),
  aws: mark("AWS", "AWS", ["amazon", "amazon web services", "cloud"]),
  azure: mark("Azure", "AZ", ["microsoft azure", "ms azure", "cloud"]),
  openai: mark("OpenAI", "OAI", ["chatgpt", "gpt", "ai"]),
  react: si(siReact, ["reactjs"]),
  vue: si(siVuedotjs, ["vuejs"]),
  angular: si(siAngular),
  svelte: si(siSvelte),
  nextjs: si(siNextdotjs, ["next"]),
  nodejs: si(siNodedotjs, ["node"]),
  deno: si(siDeno),
  bun: si(siBun),
  astro: si(siAstro),
  python: si(siPython, ["py"]),
  typescript: si(siTypescript, ["ts"]),
  javascript: si(siJavascript, ["js"]),
  go: si(siGo, ["golang"]),
  rust: si(siRust, ["rs"]),
  php: si(siPhp),
  ruby: si(siRuby, ["rb"]),
  kotlin: si(siKotlin, ["kt"]),
  swift: si(siSwift),
  dart: si(siDart),
  flutter: si(siFlutter),
  cpp: si(siCplusplus, ["c++", "cplusplus"]),
  c: si(siC),
  dotnet: si(siDotnet, [".net", "csharp", "c#"]),
  elixir: si(siElixir, ["ex"]),
  scala: si(siScala),
  haskell: si(siHaskell, ["hs"]),
  lua: si(siLua),
  r: si(siR),
  perl: si(siPerl),
  zig: si(siZig),
  solidity: si(siSolidity, ["sol", "ethereum"]),
  android: si(siAndroid),
  apple: si(siApple, ["ios", "macos"]),
  linux: si(siLinux),
  ubuntu: si(siUbuntu),
  debian: si(siDebian),
  fedora: si(siFedora),
  archlinux: si(siArchlinux, ["arch"]),
  raspberrypi: si(siRaspberrypi, ["rpi", "pi"]),
  npm: si(siNpm),
  pnpm: si(siPnpm),
  yarn: si(siYarn),
  vite: si(siVite),
  webpack: si(siWebpack),
  esbuild: si(siEsbuild),
  rollup: si(siRollupdotjs),
  babel: si(siBabel),
  eslint: si(siEslint),
  prettier: si(siPrettier),
  jest: si(siJest),
  vitest: si(siVitest),
  cypress: si(siCypress),
  storybook: si(siStorybook),
  html5: si(siHtml5, ["html"]),
  css: si(siCss),
  sass: si(siSass, ["scss"]),
  tailwindcss: si(siTailwindcss, ["tailwind"]),
  bootstrap: si(siBootstrap),
  mui: si(siMui, ["material ui"]),
  "ant-design": si(siAntdesign, ["antd"]),
  graphql: si(siGraphql, ["gql"]),
  apollo: si(siApollographql),
  prisma: si(siPrisma),
  mongodb: si(siMongodb, ["mongo"]),
  postgresql: si(siPostgresql, ["postgres", "psql"]),
  mysql: si(siMysql),
  sqlite: si(siSqlite),
  redis: si(siRedis),
  elasticsearch: si(siElasticsearch, ["elastic search"]),
  cockroachdb: si(siCockroachlabs, ["cockroach"]),
  neo4j: si(siNeo4j),
  influxdb: si(siInfluxdb),
  clickhouse: si(siClickhouse),
  snowflake: si(siSnowflake),
  databricks: si(siDatabricks),
  duckdb: si(siDuckdb),
  kafka: si(siApachekafka, ["apache kafka"]),
  rabbitmq: si(siRabbitmq, ["amqp"]),
  nginx: si(siNginx),
  apache: si(siApache, ["httpd"]),
  terraform: si(siTerraform, ["tf", "iac"]),
  opentofu: si(siOpentofu, ["tofu", "iac"]),
  ansible: si(siAnsible),
  prometheus: si(siPrometheus),
  grafana: si(siGrafana),
  datadog: si(siDatadog),
  sentry: si(siSentry),
  newrelic: si(siNewrelic, ["new relic"]),
  opentelemetry: si(siOpentelemetry, ["otel"]),
  jenkins: si(siJenkins, ["ci"]),
  circleci: si(siCircleci, ["ci"]),
  "github-actions": si(siGithubactions, ["gha", "ci"]),
  travisci: si(siTravisci, ["travis"]),
  teamcity: si(siTeamcity),
  vercel: si(siVercel),
  netlify: si(siNetlify),
  cloudflare: si(siCloudflare, ["cf"]),
  digitalocean: si(siDigitalocean, ["do"]),
  firebase: si(siFirebase),
  supabase: si(siSupabase),
  appwrite: si(siAppwrite),
  planetscale: si(siPlanetscale),
  figma: si(siFigma),
  notion: si(siNotion),
  linear: si(siLinear),
  discord: si(siDiscord),
  jira: si(siJira),
  confluence: si(siConfluence),
  trello: si(siTrello),
  asana: si(siAsana),
  miro: si(siMiro),
  postman: si(siPostman),
  insomnia: si(siInsomnia),
  swagger: si(siSwagger),
  openapi: si(siOpenapiinitiative, ["oas"]),
  intellij: si(siIntellijidea, ["idea", "jetbrains"]),
  neovim: si(siNeovim, ["nvim"]),
  vim: si(siVim),
  zed: si(siZedindustries),
  vscodium: si(siVscodium, ["vscode", "vs code", "visual studio code"]),
  pandas: si(siPandas),
  numpy: si(siNumpy),
  "scikit-learn": si(siScikitlearn, ["sklearn"]),
  opencv: si(siOpencv, ["cv"]),
  jupyter: si(siJupyter, ["notebook", "ipynb"]),
  keras: si(siKeras),
  wandb: si(siWeightsandbiases, ["weights and biases"]),
  mlflow: si(siMlflow),
  stripe: si(siStripe),
  paypal: si(siPaypal),
  auth0: si(siAuth0),
  okta: si(siOkta),
  keycloak: si(siKeycloak),
  redux: si(siRedux),
  "react-query": si(siReactquery, ["tanstack query"]),
  trpc: si(siTrpc),
  fastapi: si(siFastapi),
  django: si(siDjango),
  flask: si(siFlask),
  spring: si(siSpring, ["spring boot"]),
  express: si(siExpress, ["expressjs"]),
  nestjs: si(siNestjs, ["nest"]),
  laravel: si(siLaravel),
  unity: si(siUnity),
  blender: si(siBlender),
  threejs: si(siThreedotjs, ["three"]),
  electron: si(siElectron),
  tauri: si(siTauri),
  wasm: si(siWebassembly, ["webassembly"]),
  mdn: si(siMdnwebdocs, ["mdn web docs"]),
  stackoverflow: si(siStackoverflow, ["so", "stack overflow"]),
  youtube: si(siYoutube),
  x: si(siX, ["twitter"]),
  reddit: si(siReddit),
  medium: si(siMedium),
  hashnode: si(siHashnode),
  jaeger: si(siJaeger, ["tracing"]),
  opensearch: si(siOpensearch),
  splunk: si(siSplunk),
  elastic: si(siElastic),
  hashicorp: si(siHashicorp),
  vault: si(siVault),
  consul: si(siConsul),
  packer: si(siPacker),
  pulumi: si(siPulumi, ["iac"]),
  istio: si(siIstio, ["service mesh"]),
  linkerd: si(siLinkerd, ["service mesh"]),
  argo: si(siArgo, ["argocd", "argo cd", "gitops"]),
  flux: si(siFlux, ["gitops"]),
  sonarqube: si(siSonarqubeserver, ["sonar"]),
  sonar: si(siSonar),
  minio: si(siMinio, ["s3"]),
  traefik: si(siTraefikproxy),
  airflow: si(siApacheairflow, ["apache airflow"]),
  spark: si(siApachespark, ["apache spark"]),
  hadoop: si(siApachehadoop, ["apache hadoop"]),
  flink: si(siApacheflink, ["apache flink"]),
  looker: si(siLooker),
  metabase: si(siMetabase),
  homeassistant: si(siHomeassistant, ["ha", "home assistant"]),
  openjdk: si(siOpenjdk, ["java", "jdk"]),
  ray: si(siRay, ["ray io"]),
} as const satisfies Record<string, BrandIconDef>

export const BRAND_ICON_IDS = Object.keys(BRAND_ICONS)

export const FEATURED_BRAND_ICONS = [
  "github",
  "gitlab",
  "docker",
  "kubernetes",
  "google",
  "google-cloud",
  "aws",
  "azure",
  "openai",
  "anthropic",
  "claude",
  "huggingface",
  "python",
  "typescript",
  "react",
  "nodejs",
] as const
